compute_environment: LOCAL_MACHINE
debug: true
deepspeed_config:
  deepspeed_config_file: "zero_stage2_config.yaml"
  deepspeed_multinode_launcher: standard
  zero3_init_flag: false
distributed_type: DEEPSPEED
downcast_bf16: 'fp16'
enable_cpu_affinity: false
machine_rank: 0
main_process_ip: null
main_process_port: null
main_training_function: main
#mixed_precision: 'fp16'
num_machines: 1
num_processes: 2
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
